name: Caller
run-name: ${{ github.actor }} Microhackaton reusable workflow 🚀
on: 
  push:
  workflow_dispatch: 
jobs:
  build:
    uses: AntonioSesePerez/microHackaton16WorkFlow/.github/workflows/WFCentralizado.yaml@main 
